"use client";

import { useEffect, useState } from "react";
import AdminShell from "@/components/AdminShell";
import { useRequireSession } from "@/lib/useSession";

// Milestone AC, Part 4 — Settings foundation. The central future home
// for numbering/sequences, users, roles, permissions, and operational
// configuration.
//
// Milestone AD, Part 9 — Numbering & Sequences now has real schema and
// read APIs behind it (see lib/db/schema.ts's numberingSeries/
// numberingSequenceLedger and lib/numbering.ts's formatter), so this
// section is upgraded from a design-pending card into a genuine,
// read-only view: real (currently empty) configured series, the
// static entity-type/prefix registry, and the same formatted examples
// this milestone's own spec uses (C06001, V06001, ...). No editing —
// automatic assignment and series configuration remain future work, as
// this milestone explicitly scopes.
export default function SettingsPage() {
  const { session, loading } = useRequireSession(["ADMIN"]);
  const [series, setSeries] = useState<any[] | null>(null);
  const [entityTypes, setEntityTypes] = useState<any[]>([]);

  useEffect(() => {
    if (!session) return;
    fetch("/api/settings/numbering-series").then((r) => (r.ok ? r.json() : [])).then(setSeries);
    fetch("/api/settings/numbering-entity-types").then((r) => (r.ok ? r.json() : [])).then(setEntityTypes);
  }, [session]);

  if (loading || !session) {
    return <div className="min-h-screen bg-paper flex items-center justify-center text-steel text-sm">Loading…</div>;
  }

  const otherCards = [
    {
      title: "Users & Access",
      description: "Manage who can log in and which tenant(s) they belong to.",
      status: "Design pending / schema required",
    },
    {
      title: "Roles & Permissions",
      description: "Dispatch Supervisor, Maintenance Team, Workshop Manager, Procurement, Inventory, and other role-based access.",
      status: "Design pending / schema required",
    },
    {
      title: "Operational Settings",
      description: "Tenant-level configuration for dispatch, maintenance, and procurement workflows.",
      status: "Design pending / schema required",
    },
  ];

  return (
    <AdminShell title="Settings">
      <div className="p-6 max-w-4xl mx-auto space-y-4">
        <div>
          <h1 className="text-lg font-semibold">Settings</h1>
          <p className="text-steel text-sm mt-0.5">The central place for platform configuration — numbering, users, roles, permissions, and operational settings.</p>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-4 space-y-3">
          <h3 className="font-medium text-sm">Numbering & Sequences</h3>
          <p className="text-steel text-sm">Standardized, autogenerated reference numbers for customers, suppliers, trips, expenses, PRs, POs, and more.</p>
          <p className="text-warn text-xs bg-warn/10 rounded-lg px-2 py-1.5">Configuration UI and automatic assignment will be added in later milestones. No existing records have been renumbered.</p>

          <div>
            <p className="text-steel text-xs uppercase tracking-wide mb-1">Configured series</p>
            {series === null ? (
              <p className="text-steel text-sm">Loading…</p>
            ) : series.length === 0 ? (
              <p className="text-steel text-sm">No numbering series configured yet.</p>
            ) : (
              <table className="w-full text-sm">
                <thead className="text-steel text-xs uppercase"><tr><th className="text-left py-1">Entity</th><th className="text-left py-1">Prefix</th><th className="text-left py-1">Next</th><th className="text-left py-1">Status</th></tr></thead>
                <tbody>
                  {series.map((s: any) => (
                    <tr key={s.id} className="border-t border-slate-50">
                      <td className="py-1">{s.displayName}</td>
                      <td className="py-1 font-mono text-xs">{s.prefix}</td>
                      <td className="py-1">{s.nextNumber}</td>
                      <td className="py-1 text-steel">{s.status}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>

          <div>
            <p className="text-steel text-xs uppercase tracking-wide mb-1">Supported entity types</p>
            <div className="flex flex-wrap gap-1.5">
              {entityTypes.map((et: any) => (
                <span key={et.entityType} className="text-xs bg-paper rounded px-2 py-0.5">{et.label} ({et.recommendedPrefix})</span>
              ))}
            </div>
          </div>

          <div>
            <p className="text-steel text-xs uppercase tracking-wide mb-1">Format examples</p>
            <div className="flex flex-wrap gap-1.5 font-mono text-xs">
              {["C06001", "V06001", "PR06001", "PO06001", "GR06001"].map((ex) => (
                <span key={ex} className="bg-paper rounded px-2 py-0.5">{ex}</span>
              ))}
            </div>
          </div>
        </div>

        <div className="grid sm:grid-cols-2 gap-4">
          {otherCards.map((c) => (
            <div key={c.title} className="bg-white rounded-xl border border-slate-200 p-4 space-y-2">
              <h3 className="font-medium text-sm">{c.title}</h3>
              <p className="text-steel text-sm">{c.description}</p>
              <p className="text-warn text-xs bg-warn/10 rounded-lg px-2 py-1 inline-block">{c.status}</p>
            </div>
          ))}
        </div>
      </div>
    </AdminShell>
  );
}
