"use client";

import AdminShell from "@/components/AdminShell";
import { useRequireSession } from "@/lib/useSession";

// Milestone AC, Part 4 — Settings foundation. The central future home
// for numbering/sequences, users, roles, permissions, and operational
// configuration. None of that schema exists yet (see this milestone's
// own numbering and security audits) — every card below is honest
// about what's implemented (nothing operational yet) versus planned.
// No fake roles, no fake sequences, no fake users are shown.
export default function SettingsPage() {
  const { session, loading } = useRequireSession(["ADMIN"]);
  if (loading || !session) {
    return <div className="min-h-screen bg-paper flex items-center justify-center text-steel text-sm">Loading…</div>;
  }

  const cards = [
    {
      title: "Numbering & Sequences",
      description: "Standardized, autogenerated reference numbers for customers, suppliers, trips, expenses, PRs, POs, and more.",
      status: "Design pending / schema required",
    },
    {
      title: "Users & Access",
      description: "Manage who can log in and which tenant(s) they belong to.",
      status: "Design pending / schema required",
    },
    {
      title: "Roles & Permissions",
      description: "Dispatch Supervisor, Maintenance Team, Workshop Manager, Procurement, Inventory, and other role-based access.",
      status: "Design pending / schema required",
    },
    {
      title: "Operational Settings",
      description: "Tenant-level configuration for dispatch, maintenance, and procurement workflows.",
      status: "Design pending / schema required",
    },
  ];

  return (
    <AdminShell title="Settings">
      <div className="p-6 max-w-4xl mx-auto space-y-4">
        <div>
          <h1 className="text-lg font-semibold">Settings</h1>
          <p className="text-steel text-sm mt-0.5">The central place for platform configuration — numbering, users, roles, permissions, and operational settings.</p>
        </div>

        <div className="grid sm:grid-cols-2 gap-4">
          {cards.map((c) => (
            <div key={c.title} className="bg-white rounded-xl border border-slate-200 p-4 space-y-2">
              <h3 className="font-medium text-sm">{c.title}</h3>
              <p className="text-steel text-sm">{c.description}</p>
              <p className="text-warn text-xs bg-warn/10 rounded-lg px-2 py-1 inline-block">{c.status}</p>
            </div>
          ))}
        </div>
      </div>
    </AdminShell>
  );
}
